name: cube_transition
description: A nice 3D Cube effect for your PageView and PageRoute transitions.
version: 1.0.2

homepage: https://aeyrium.com/products/mxtracker/
repository: https://github.com/aeyrium/cube_transition

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:

flutter: